@startuml
'https://plantuml.com/class-diagram

+class Application{
+void start(Stage primaryStage)
+void main(String[] args)
}

+class Item{
-String itemName
-String description
-String dueDate
-boolean completed
+Item(String itemName)
+Item(String itemName, String description, String dueDate)
+Item(String itemName, boolean completed)
+Item(String itemName, String description, String dueDate, boolean completed)
+String toString()
-boolean validateDueDate(String dueDate)
+void setDescription(String description)
+void setDueDate(String dueDate)
+void setCompleted(boolean completed)
}

+class ToDoList{
-String title
-ArrayList<Item> itemList
+ToDoList(String title, List<Item> itemList)
+boolean validateToDoList
+boolean validateTitle
+void addItemToList
+void removeItemFromList
}

+class TitleScreenController{

}

+class ListEditorController{
}

+class ViewListsScreenController{
}

+class ViewOneListController{
}

Item --* "ToDoList has Items" ToDoList
Application -- "launches" TitleScreenController
TitleScreenController <--> ListEditorController
TitleScreenController <-->  ViewListsScreenController
ViewListsScreenController <--> ViewOneListController
ViewListsScreenController --> ListEditorController
ViewOneListController --> ListEditorController
ListEditorController --* "edits" ToDoList
ListEditorController --* "edits" Item
ViewListsScreenController --* "displays" ToDoList
ViewOneListController --* "displays" ToDoList
ViewOneListController --* "displays" Item






@enduml